site_name="Drawing, Moving and Seeing with Code - Fall 2026"
site_url=https://leetusman.com/dmsc_fall2026
site_description="Website for the course Drawing, Moving and Seeing with Code at Purchase College, fall 2026"
site_feed=rss.xml
site_dir=docs
site_posts=posts
site_assets=images
site_theme=dmsc.css
